name: Express API CI
run-name: Express API CI is running.
on: 
    push:
        branches:
            - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [23.7.0]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Test
        run: npm run test
        
      - name: Run E2E tests
        run: |
          npm run start &
          echo "Server is Running ....."
          sleep 10 # wait 10 seconds
          npm run e2e
    
  
